### ISSUE TITLE
image error with 1.3.2

### ISSUE THREAD

**Issue by smolleyes** [optilude/xlsx-template#168]
hi

i have this error with 1.3.2 and can t get any image working with any other version :(

` TypeError: Cannot read properties of null (reading 'asText')
1|extranet-api  | 2022-08-26 15:23 +02:00:       at Workbook.module.exports.Workbook.loadDrawing (/home/srv/websites/batexpert-api/node_modules/xlsx-template/lib/index.js:592:77)`

someone have success adding images with this module ? 

thanks

**Comment by smolleyes** [comment]
hi

someone still maintaining this module ? 

thanks

**Comment by Eraledm** [comment]
Same issue here

**Comment by Eraledm** [comment]
I forked the repo and it looks like tests are working correctly so I tested with my own xlsx file and turns out an embedded image was breaking this feature:
<img width="420" alt="Screen Shot 2022-11-18 at 10 34 52 p m" src="https://user-images.githubusercontent.com/34149908/202834249-a15112ae-91a0-47b4-8b9c-1fdd55114695.png">
I haven't had time to check the code and figure out what's the real issue, I tested removing that image and adding other png images and it works as expected, so my current solution was just remove that image and add another one.

Hope it helps

**Comment by kant2002** [comment]
If somebody have file and short sample of code that may help troubleshoot an issue

**Comment by Eraledm** [comment]
Sure, 
[test-insert-images.xlsx](https://github.com/optilude/xlsx-template/files/10046240/test-insert-images.xlsx)
The original excel was from a client, I modified it to keep the same format of the testing files so you can delete the image object and validate that the tests passes but if you keep the image then the tests fails

**Comment by kant2002** [comment]
@Eraledm can you take a look at release 1.4.0 and I was not able to repro an issue. Maybe you can create some small repro app ?

**Comment by smolleyes** [comment]
hello

have another problem here... (with 1.4.0)

TypeError: Cannot read properties of null (reading 'asText') at Workbook.module.exports.Workbook.loadDrawing (...node_modules/xlsx-template/lib/index.js:516:77)

 i don t have any image in my template :/

if i add some logs:
drawing.filename = drawingFilename;
drawing.root = drawingTree.getroot();
drawing.relFilename = path.dirname(drawingFilename) + '/_rels/' + path.basename(drawingFilename) + '.rels';

console.log(drawing.filename,drawing.root, drawing.relFilename, self.archive.file, self.archive.file(drawing.relFilename))

result:

`xl / drawings / drawing1.xml

Element {
   _id: 722,
   tag: 'xdr:wsDr',
   attrib: {
     'xmlns:xdr': 'http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing',
     'xmlns:a': 'http://schemas.openxmlformats.org/drawingml/2006/main'
   },
   text: '',
   tail: null,
   _children: [
     Element {
       _id: 723,
       tag: 'mc:AlternateContent',
       attrib: [Object],
       text: '',
       tail: '',
       _children: [Array]
     },
     Element {
       _id: 768,
       tag: 'mc:AlternateContent',
       attrib: [Object],
       text: '',
       tail: '',
       _children: [Array]
     },
     Element {
       _id: 813,
       tag: 'mc:AlternateContent',
       attrib: [Object],
       text: '',
       tail: '',
       _children: [Array]
     },
     Element {
       _id: 858,
       tag: 'mc:AlternateContent',
       attrib: [Object],
       text: '',
       tail: '',
       _children: [Array]
     }
   ]
}

xl / drawings / _rels / drawing1.xml.rels[Function: file]

null`

an idear?

thanks!

**Comment by smolleyes** [comment]
hi!

in my case it seems that the checkbox are creating the problem... if i remove them everything works... for information

**Comment by kant2002** [comment]
@smolleyes do you experience this error with 1.4.0 too?

**Comment by smolleyes** [comment]
with the "bad" excel yes

**Comment by kant2002** [comment]
@smolleyes can you give me test file similar to wha Eraledm provide which trigger this behaviour?

**Comment by interrizky** [comment]
Upgrade it to 1.4.3 version and still having the issue. Have tried using buffer, base64 and path too. It says: 

> TypeError: Cannot read properties of null (reading 'asText') at Workbook.loadDrawing (../node_modules/xlsx-template/lib/index.js:517:77)
