### ISSUE TITLE
Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by xxxx96923** [optilude/xlsx-template#196]
import XlsxTemplate from "xlsx-template";

const template = new XlsxTemplate(data);

TypeError: Cannot read properties of undefined (reading 'call')
    at new Queue (index.js:12:16)
    at node_modules/.pnpm/image-size@1.1.1/node_modules/image-size/dist/index.js (index.js:13:15)
    at __require2 (chunk-LK32TJAX.js?v=6aff3c6a:18:50)
    at node_modules/.pnpm/xlsx-template@1.4.4/node_modules/xlsx-template/lib/index.js (index.js:7:14)
    at __require2 (chunk-LK32TJAX.js?v=6aff3c6a:18:50)
    at index.js:1610:18

**Comment by kant2002** [comment]
What’s the structure of the data which are passed to the library? Would be great to have small snippet of code which reproduce the problem.

**Comment by xxxx96923** [comment]
import XlsxTemplate from "xlsx-template";
import JSZipUtils from "jszip-utils";
import { saveAs } from "file-saver";
export const exportXlsx = (tempXlsxPath, item, fileName, option = {}) => {
  JSZipUtils.getBinaryContent(tempXlsxPath, (error, data: Buffer) => {
    if (error) {
      throw error;
    }
    const template = new XlsxTemplate(data, option);
    // const sheetNumber = 1;
    // template.substitute(sheetNumber, item);
    // let templateData = template.generate({ type: "blob" });
    // saveAs(templateData, `${fileName}.xlsx`);
  });
};


error line:   const template = new XlsxTemplate(data, option);

**Comment by kant2002** [comment]
It would be hard for me to guess what exactly happens. Can you show shape of the `data` object. and template which reproduce the issue. You may try to remove sensetive information from the template to not disclose your customer.

**Comment by xxxx96923** [comment]
![微信截图_20241027091935](https://github.com/user-attachments/assets/c7e4a797-d702-4c8c-a759-b1009edf580f)

Did not call exportXlsx method, is the site initialization when the error, I have not passed the data

**Comment by xxxx96923** [comment]
As soon as I opened the relevant page, the console reported an error. I haven't clicked the export button yet

**Comment by xxxx96923** [comment]
I added console.log and found that the exportXlsx method did not enter, but it just reported an error
